/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author emmor
 */
public class vtnP extends javax.swing.JFrame
{
    
    int xMouse, yMouse;
    
    /**
     * Creates new form vtnP
     */
    public vtnP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        btnExitt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JPanel();
        vtnUsuarioo = new javax.swing.JLabel();
        btnAdimn = new javax.swing.JPanel();
        btnAdminn = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(233, 144));

        background.setBackground(new java.awt.Color(152, 193, 217));
        background.setToolTipText("");
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Codec Cold Trial", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(50, 57, 85));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Sistema Alberca");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 550, -1));

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnExitt.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnExitt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExitt.setText("X");
        btnExitt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExitt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnExittMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 0, -1, -1));

        header.setBackground(new java.awt.Color(152, 193, 217));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 30));

        btnUsuario.setBackground(new java.awt.Color(238, 108, 77));

        vtnUsuarioo.setBackground(new java.awt.Color(238, 108, 77));
        vtnUsuarioo.setFont(new java.awt.Font("Codec Cold Trial", 0, 12)); // NOI18N
        vtnUsuarioo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vtnUsuarioo.setText("Usuario");
        vtnUsuarioo.setToolTipText("");
        vtnUsuarioo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vtnUsuarioo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vtnUsuariooMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vtnUsuarioo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vtnUsuarioo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 40));

        btnAdimn.setBackground(new java.awt.Color(61, 90, 128));
        btnAdimn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAdminn.setFont(new java.awt.Font("Codec Cold Trial", 0, 12)); // NOI18N
        btnAdminn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdminn.setText("Administrador");

        javax.swing.GroupLayout btnAdimnLayout = new javax.swing.GroupLayout(btnAdimn);
        btnAdimn.setLayout(btnAdimnLayout);
        btnAdimnLayout.setHorizontalGroup(
            btnAdimnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAdimnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdminn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAdimnLayout.setVerticalGroup(
            btnAdimnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAdimnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdminn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(btnAdimn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 120, 40));

        txtEntrada.setForeground(new java.awt.Color(50, 57, 85));
        txtEntrada.setText("Seleccione una opcion");
        background.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vtnUsuariooMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vtnUsuariooMouseClicked
    {//GEN-HEADEREND:event_vtnUsuariooMouseClicked
        new vtnUsuario().setVisible(true);
    }//GEN-LAST:event_vtnUsuariooMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_headerMousePressed
    {//GEN-HEADEREND:event_headerMousePressed
        xMouse = evt.getX(); 
        yMouse = evt.getY();
        
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_headerMouseDragged
    {//GEN-HEADEREND:event_headerMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnExittMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnExittMouseClicked
    {//GEN-HEADEREND:event_btnExittMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExittMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAdimn;
    private javax.swing.JLabel btnAdminn;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel btnExitt;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel vtnUsuarioo;
    // End of variables declaration//GEN-END:variables
}
